[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/jeonck"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
